"""AI generation schemas: SceneCard, SceneDraft, Context Pack."""

from pydantic import BaseModel, Field


class SceneCard(BaseModel):
    """Structured scene card generated by Instructor."""
    title: str = Field(description="场景标题")
    location: str = Field(description="场景地点")
    time: str = Field(description="时间")
    characters: list[str] = Field(description="出场人物列表")
    conflict: str = Field(description="核心冲突")
    turning_point: str = Field(default="", description="转折点")
    reveal: str = Field(default="", description="揭示/悬念")
    target_chars: int = Field(
        default=1500, description="目标字数"
    )


class SceneCardRequest(BaseModel):
    chapter_id: int
    scene_id: int
    hints: str = Field(
        default="", description="用户对场景的补充说明"
    )


class SceneDraftRequest(BaseModel):
    scene_id: int
    scene_card: SceneCard


class ChapterSummaryModel(BaseModel):
    """Structured chapter summary extracted by Instructor."""
    narrative: str = Field(
        description="1-2 段叙事总结"
    )
    key_events: list[str] = Field(
        description="关键事件列表"
    )
    keywords: list[str] = Field(
        description="关键词"
    )
    entities: list[str] = Field(
        description="出场实体（人物、地点、物品）"
    )
    plot_threads: list[str] = Field(
        default_factory=list, description="情节线索"
    )


class RewriteRequest(BaseModel):
    scene_id: int
    text: str = Field(description="当前场景正文")
    target_chars: int = Field(
        default=1500, ge=100, le=50000,
        description="目标字数",
    )
    mode: str = Field(
        description="重写模式: expand 或 compress",
        pattern="^(expand|compress)$",
    )


class WordCountCheck(BaseModel):
    status: str = Field(description="within / over / under")
    actual_chars: int
    target_chars: int
    delta: int
    deviation: float
    suggestion: str | None = Field(
        default=None, description="compress / expand / None"
    )
